# Generated by Django 5.0.2 on 2024-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='condact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Condact_Number', models.IntegerField(max_length=12)),
                ('Email_id', models.EmailField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Course_Details', models.CharField(max_length=100)),
            ],
        ),
    ]
